### ISSUE TITLE
Types for repo

### ISSUE THREAD

**Issue by famouspotatoes** [blinkdog/telnet-stream#10]
I know its an old repo, but I found this package to be very valuable. Hopefully we can put together a typescript declaration for it.

**Comment by blinkdog** [comment]
A contributor has submitted a typescript declaration PR in #9 
How do those declarations look to you?

I must admit that I don't have a lot of experience with typescript yet.
Although I am open to adding a declaration to this package and publishing it on npm.

**Comment by famouspotatoes** [comment]
This is a perfect solution. I will use the fork in the meantime, but do you want to merge it into the repo & publish new version to npm? 

Btw I have tried many other telnet packages (not just javascript, also PHP) and yours is the best, hands down.

**Comment by blinkdog** [comment]
> This is a perfect solution. I will use the fork in the meantime, but do you want to merge it into the repo & publish new version to npm?
> 
> Btw I have tried many other telnet packages (not just javascript, also PHP) and yours is the best, hands down.

I've pushed version 1.0.5 to npm.
Could you give it a try and let me know if the TypeScript definitions are working properly for you?

And thank you for the high praise for this package. I'm glad you've found it useful. :smile:
